name: Testing PRs to master

on:
  pull_request:
    branches: [master]

jobs:
  push_to_registry:
    name: Push test Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: nh273/alpha-zero:${{ github.event.number }} # use PR number as tag
  build:
    needs: push_to_registry
    name: Pytest in Pipenv
    runs-on: ubuntu-latest
    container:
      image: docker://nh273/alpha-zero:${{ github.event.number }}
    steps:
      - uses: actions/checkout@v2
      - name: Test with pytest
        run: pipenv run pytest .
